filter:
  dependency_paths:
    - vendor/
  excluded_paths:
    - tests/
    - vendor/

build:
  cache:
    directories:
      - vendor/
  nodes:
    analysis:
      dependencies:
        override:
          - true
      tests:
        override:
          - php-scrutinizer-run --sub-project-dir=src/
          - phpcs-run --standard=.phpcs.xml
